name: pandas-release
channels:
    - defaults
    - conda-forge
dependencies:
    - packaging
    - conda-build
    - conda-smithy
    - conda-forge-pinning
    - lxml
    - twine
    # web
    - markdown
    - feedparser
    - pyyaml
    - requests
    - jinja2

